### ISSUE TITLE
Antd 4 update

### ISSUE THREAD

**Issue by jstorm31** [AckeeCZ/create-react-app#10]
I tried to update to ant design version 4 on my personal project using our CRA fork and needed to disable `webpack-ant-icon-loader` in `react-scripts/custom/config/transfomrWebpackConfig.js`:

```diff
const preloaders = [
- {
-   loader: require.resolve('webpack-ant-icon-loader'),
-   enforce: 'pre',
-   include: [require.resolve('@ant-design/icons/lib/dist')],
- },
];
```

 Is the loader needed with antd 4 anymore? If not, I'd fire a PR. Apart from that there haven't been any problems with the migration so far.

**Comment by cermakjiri** [comment]
This has been solved. It's now possible to manually upgrade to antd@4.
