### ISSUE TITLE
Failing font apply in Fela

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/create-react-app#13]
There is a bug in `applyFonts`. A better solution is to use functional programming:
```
const applyFonts = (renderer, fonts) => {
    fonts.forEach(({ name, files, options }) => {
        renderer.renderFont(name, files, options);
    });
};
```

**Comment by baierjak** [comment]
You could directly create a pull request in this case, Marek

**Comment by cermakjiri** [comment]
Ok, `forEach` is possible to use, but wouldn't be better to just fix the current version by removing the `[]` braces? As follows:

From:
```js
const applyFonts = (renderer, fonts) => {
    for (const [{ name, files, options }] of fonts) {
        renderer.renderFont(name, files, options);
    }
};
```
to:
```js
const applyFonts = (renderer, fonts) => {
    for (const { name, files, options } of fonts) {
        renderer.renderFont(name, files, options);
    }
};
```

**Comment by jancama2** [comment]
> You could directly create a pull request in this case, Marek

No time :D

**Comment by jancama2** [comment]
> Ok, `forEach` is possible to use, but wouldn't be better to just fix the current version by removing the `[]` braces? As follows:
> 
> From:
> 
> ```js
> const applyFonts = (renderer, fonts) => {
>     for (const [{ name, files, options }] of fonts) {
>         renderer.renderFont(name, files, options);
>     }
> };
> ```
> 
> to:
> 
> ```js
> const applyFonts = (renderer, fonts) => {
>     for (const { name, files, options } of fonts) {
>         renderer.renderFont(name, files, options);
>     }
> };
> ```

Well, if it works, why not.
