### ISSUE TITLE
yarn start & wait-on fails on version 1.0.11

### ISSUE THREAD

**Issue by jstorm31** [AckeeCZ/create-react-app#14]
Upgrading to the newest version `1.0.11` causes my `yarn cypress:ci` task to be stuck on "Starting the app...", but it never starts. Furthermore, if I go to localhost:3001 in a browser, it returns "Connection refused" error. I'm not sure how to debug this. It also fails on Travis CI. It works fine for `1.0.7`.

The task in `package.json`:
```
"cypress:ci": "PORT=3001 yarn start & yarn wait-on http://localhost:3001; cypress run",
```

**Comment by cermakjiri** [comment]
I can confirm the issue but have no idea why that's happening. However, there's `start-server-and-test` package that seems to work fine:

```json
"cypress:run": "cypress run",
"cypress:ci": "PORT=3001 start-server-and-test start http://localhost:3001 cypress:run"
```

**Comment by jstorm31** [comment]
Great, this library works well, thanks 🙂
