### ISSUE TITLE
Core Redux component from function to class

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/create-react-app#17]
As Fela component was rewritten into class component to avoid re-rendering styles, wouldn't it be better to do the same for Redux? There shouldnt be a problem since it is one of the top level components and never re-renders but just to be sure.

I mean [this code](https://github.com/AckeeCZ/create-react-app/blob/master/packages/react-scripts/template/src/modules/core/modules/redux/components/Redux.jsx).

**Comment by cermakjiri** [comment]
Ye, it would. Good point, I'll fix.
