### ISSUE TITLE
ConnectedReactRouter forcing the whole app to instantly re-render on every store change.

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/create-react-app#24]
### What We Know So Far
1) Looks like `connected-react-router@6.0.0` is forcing the app to re-render on every store change
2) There are some improvements in version 6.1.0 but there is an issue with version 6.2.1 still complaining about re-renders https://github.com/supasate/connected-react-router/issues/242

### Connected Issues
* The problem is that in version `6.1.0` and highter action creators `push` etc. are not working.
* Either pushing and object is not working with `6.1.0.` and higher

### What To Do?
* Would be nice to try skeleton without `connected-react-router` to see the behavior with normal `react-router`
* Minimal app with some easy form would show us if there is any improvement with and without `connected-react-router`
*I expect that without `connected-react-router` just the form fields would be re-rendered while with it  the whole app would be re-rendering.

* **Maybe we should consider not using `connected-react-router`** ?

**Comment by jancama2** [comment]
Looks like the problem can be solved by reinstalling `react-router-dom`. I have tried to use `@4.4.0-beta.7` and all the problems are solved. Combination with `connected-react-router@6.3.1` works for me just fine.

**Comment by jancama2** [comment]
PS `@4.4.0-beta.7` looks stable enough to be used.

**Comment by cermakjiri** [comment]
The stable `@4.4.0` version has been just released 🎉
