### ISSUE TITLE
TS Template Small Updates

### ISSUE THREAD

**Issue by cermakjiri** [AckeeCZ/create-react-app#45]
- [x] add strict mode - React.StrictMode component
- [x] add web vitals - See latest CRA template, it's there
- [x] add renovate.json
- [x] add .cf-purge-urls.yaml (e.g. from FN CMS project)
- [ ] add .gcs-cache-control (e.g. from FN CMS project)
- [x] Make sure the MR checklist is there
- [x] Set CI by default to true

**Comment by jstorm31** [comment]
> add web vitals - See latest CRA template, it's there

https://create-react-app.dev/docs/measuring-performance/

@cermakjiri How do you intent to monitor this? We don't have any reporting service. I suggest we use Sentry. It offers measuring performance including [WebVitals](https://docs.sentry.io/product/performance/web-vitals/). It should be set up per project then, not in the template.

**Comment by cermakjiri** [comment]
> > add web vitals - See latest CRA template, it's there
> 
> https://create-react-app.dev/docs/measuring-performance/
> 
> @cermakjiri How do you intent to monitor this? We don't have any reporting service from this. I'd suggest we use Sentry for this. It offers measuring performance including [WebVitals](https://docs.sentry.io/product/performance/web-vitals/). It should be set up per project then, not in the template.

The output is [fairly variable](https://create-react-app.dev/docs/measuring-performance) and can be sent to multiple analytics providers. The package can be easily [lazy loaded](https://github.com/facebook/create-react-app/blob/main/packages/cra-template-typescript/template/src/reportWebVitals.ts). And I hope we'll more focus on this if it's going to be included in the template. The implementation can be the same as it's in [the original one](https://github.com/facebook/create-react-app/blob/main/packages/cra-template-typescript/template/src/index.tsx).

**Comment by cermakjiri** [comment]
> > add web vitals - See latest CRA template, it's there
> 
> https://create-react-app.dev/docs/measuring-performance/
> 
> @cermakjiri How do you intent to monitor this? We don't have any reporting service from this. I'd suggest we use Sentry for this. It offers measuring performance including [WebVitals](https://docs.sentry.io/product/performance/web-vitals/). It should be set up per project then, not in the template.

Ok, let's do it with Sentry as the default option.

**Comment by jstorm31** [comment]
Skipping `.gcs-cache-control` since we now deploy to Firebase hosting, not GCP bucket.
