### ISSUE TITLE
Upgrade to antd v4

### ISSUE THREAD

**Issue by cermakjiri** [AckeeCZ/create-react-app#48]
- The version 3.x doesn't support code-splitting very well. Due to that, the bundle is unnecessarily big.
- v4 version supports virtualized lists which would be useful for example for select inputs.

**Comment by jstorm31** [comment]
This depends on resolving `@ackee/mateus` package in #62 and #47, because there are Antd 3 bindings in mateus.

**Comment by jstorm31** [comment]
The team agreed on removing `@ackee/mateus` and `antd` dependencies completely (they should be installed per project). `auth` module can use simple html fields for now.
